# Generated by Django 5.2.1 on 2025-05-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='user_answer',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
