# Generated by Django 5.2.1 on 2025-05-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='correct_questions',
            field=models.TextField(blank=True),
        ),
    ]
