# Generated by Django 5.2.1 on 2025-05-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_category_question_choice_userquiz_userquizoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='correct_answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='user_answer',
            field=models.TextField(default=''),
        ),
    ]
