# Generated by Django 5.2.1 on 2025-05-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizresult_correct_questions'),
        ('quiz', '0002_remove_quizresult_correct_answer_and_more'),
    ]

    operations = [
    ]
