# Generated by Django 5.2.1 on 2025-05-23 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizresult_correct_answer_quizresult_question_and_more'),
    ]

    operations = [
    ]
