# Generated by Django 5.2 on 2025-05-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizresult_correct_answer_quizresult_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
