# Generated by Django 5.2.1 on 2025-05-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20250523_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizresult',
            options={'ordering': ['-played_at']},
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='user_answer',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='questions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='difficulty',
            field=models.CharField(max_length=20),
        ),
    ]
