# Generated by Django 5.2.1 on 2025-05-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_quizresult_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizresult',
            options={},
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='questions',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='correct_answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='user_answer',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='difficulty',
            field=models.CharField(max_length=50),
        ),
    ]
