# Generated by Django 5.2 on 2025-05-24 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizresult_duration'),
        ('quiz', '0006_alter_quizresult_options_remove_quizresult_questions_and_more'),
    ]

    operations = [
    ]
